# Blueprint для розгортання Mapproject
services:
  # Сервіс бекенду (Django Web Service)
  - type: web
    name: mapproject-backend
    env: docker
    plan: free # або starter
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /admin/login/ # Шлях для перевірки, що сервіс живий
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: postgres-db-managed # Це посилається на addon нижче
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-channels # Це посилається на addon нижче
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-site.onrender.com # Змініть на реальний URL фронтенду
      - key: CSRF_TRUSTED_ORIGINS
        value: https://your-frontend-site.onrender.com # Змініть на реальний URL фронтенду

  # Статичний сайт для фронтенду
  - type: static
    name: mapproject-frontend
    rootDir: frontend
    plan: free
    buildCommand: "npm install && npm run build" # Assumes vite.config.js is correctly set up
    staticPublishPath: ./frontend/dist
    envVars:
      # This key will need to be added manually in the Render dashboard for security.
      - key: VITE_Maps_API_KEY
        sync: false
      # The base URL for the API that the frontend will call.
      - key: VITE_API_BASE_URL
        value: https://mapproject-backend.onrender.com # URL твого бекенду (це вже є правильно)

addons:
  # Managed PostgreSQL Database. Render handles backups, scaling, etc.
  - type: postgres
    name: postgres-db-managed
    databaseName: mapproject_db
    user: mapproject_user
    plan: free

  # Managed Redis instance for Channels (WebSocket message broker)
  - type: redis
    name: redis-channels
    plan: free
