# Generated by Django 5.2.3 on 2025-07-11 21:43

import core_api.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/DefaultProfile.png', upload_to=core_api.models.user_avatar_path),
        ),
    ]
