# Generated by Django 5.2.3 on 2025-07-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=7),
        ),
    ]
