# Generated by Django 5.2.3 on 2025-07-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_profile_chat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
