# Generated by Django 5.2.3 on 2025-07-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0012_profile_current_xp_profile_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoundAnonymousMessage',
        ),
    ]
